version: '{build}'

os: Visual Studio 2015

environment:
  matrix:
    - arch: x64
      toolenv: cygwin
      compiler: gcc
      backend: ninja
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

platform:
  - x64

branches:
  only:
    - master

init:
  - ps: |
        If($Env:compiler -like 'msvc2010') {
          Set-WinSystemLocale de-DE
          Start-Sleep -s 5
          Restart-Computer
        }

install:
  - cmd: set "ORIG_PATH=%PATH%"
  # Use a Ninja with QuLogic's patch: https://github.com/ninja-build/ninja/issues/1219
  - cmd: set "MESON_FIXED_NINJA=1"
  - call ci\appveyor_%toolenv%.bat install

build_script:
  - call ci\appveyor_%toolenv%.bat build_script

test_script:
  - cmd: echo Running tests for %arch% and %toolenv% %compiler% with the %backend% backend
  - call ci\appveyor_%toolenv%.bat test_script

on_finish:
  - set "PATH=%ORIG_PATH%"
  - appveyor PushArtifact meson-test-run.txt -DeploymentName "Text test logs"
  - appveyor PushArtifact meson-test-run.xml -DeploymentName "XML test logs"

cache:
  - C:\cache
