name: CI image builder

concurrency:
  group: img_builder-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - 'ci/ciimage/**'
      - '.github/workflows/images.yml'

  pull_request:
    branches:
      - master
    paths:
      - 'ci/ciimage/**'
      - '.github/workflows/images.yml'

  # Rebuild the images every week (Sunday)
  schedule:
    - cron: '0 0 * * 0'

  # ... or on demand
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-windows:
    env:
      HAS_DOCKER_CREDENTIALS: ${{ secrets.DOCKER_PASSWORD != '' }}
    name: ${{ matrix.cfg.name }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { name: Cygwin Windows,   id: cygwin     }
    steps:
      - run: git config --global core.autocrlf input

      - uses: actions/checkout@v3

      # Login to dockerhub
      - name: Docker login
        if:   (github.event_name == 'push' || github.event_name == 'schedule') && env.HAS_DOCKER_CREDENTIALS == 'true'
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and test
      - name: Building the ${{ matrix.cfg.id }} image
        run:  docker build -t ${{ github.repository_owner }}/${{ matrix.cfg.id }} ./ci/ciimage/cygwin/
      - name: Testing the ${{ matrix.cfg.id }} image
        run:  docker run --rm ${{ github.repository_owner }}/${{ matrix.cfg.id }} 'bash --version'

      # Publish
      - name: Push the ${{ matrix.cfg.id }} image
        run:  docker push ${{ github.repository_owner }}/${{ matrix.cfg.id }}
        if:   (github.event_name == 'push' || github.event_name == 'schedule') && env.HAS_DOCKER_CREDENTIALS == 'true'
